apps/eventapp/urls.py
from django.conf.urls import url
from . import views
app_name = "eventapp"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^add$', views.add, name='add'),
    url(r'^addevent$', views.addevent, name='addevent'),
    url(r'^addactivity/(?P<event_id>\d+)$', views.addactivity, name='addactivity'),
    url(r'^addgoal/(?P<event_id>\d+)$', views.addgoal, name='addgoal'),
    url(r'^view/(?P<event_id>\d+)$', views.view, name='view'),
    url(r'^join/(?P<event_id>\d+)$', views.join, name='join'),
]

events/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginapp.urls', namespace = "loginapp")),
    url(r'^main/', include('apps.eventapp.urls', namespace = "eventapp")),
]

trips/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginapp.urls', namespace = "loginapp")),
    url(r'^main/', include('apps.tripapp.urls', namespace = "tripapp")),
]

apps/tripapp/templates/tripapp/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'tripapp:index' %}">Home</a>
    <a href="{% url 'tripapp:logout' %}">Logout</a><br>
    <h1>Add a Trip</h1>
    <form action = "{% url 'tripapp:addTrip' %}", method = "POST">
        {% csrf_token %}
    Destination: <input type="text" name="destination"><br>
    Description: <input type="text" name="description"><br>
    Travel Date From: <input type="date" name="travel_from"><br>
    Travel Date To: <input type="date" name="travel_to"><br>
    <input type="submit" name= value="Submit">
    </form>
    {%for message in messages%}
        <p>{{message}}</p>
    {%endfor%}
</body>
</html>