apps/loginapp/urls.py
from django.conf.urls import url
from . import views
app_name = "loginapp"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^register$', views.register, name="register"),
    url(r'^login$', views.login, name="login"),
]

events/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginapp.urls', namespace = "loginapp")),
    url(r'^main/', include('apps.eventapp.urls', namespace = "eventapp")),
]

trips/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginapp.urls', namespace = "loginapp")),
    url(r'^main/', include('apps.tripapp.urls', namespace = "tripapp")),
]

apps/loginapp/models.py
from __future__ import unicode_literals
from django.db import models
import re, bcrypt
from django.contrib import messages
class UserManager(models.Manager):
    def register(self,postData):
        result = {'status':True, 'error':[]}
        if not postData['name'] or postData['name'] < 3:
            result['status'] = False
            result['error'].append('Name must be at least 3 characters')
        if not postData['username'] or postData['username'] < 3:
            result['status'] = False
            result['error'].append('Username must be at least 3 characters')
        if not postData['password'] or postData['password'] < 8:
            result['status'] = False
            result['error'].append('Password must be at least 8 characters')
        if not postData['cpassword'] or postData['cpassword'] != postData['password']:
            result['status'] = False
            result['error'].append('Passwords must match')
        if result['status'] == True:
            if User.objects.filter(username = postData['username']):
                result['status'] = False
                result['error'].append('User already exist')
            else:
                password = postData['password'].encode('utf-8')
                hashedpw = bcrypt.hashpw(password,bcrypt.gensalt(12))
                User.objects.create(
                    name = postData['name'],
                    username = postData['username'],
                    password = hashedpw,
                )
        return result
    def login(self,postData, sessionData):
        user = User.objects.filter(username = postData['username'])
        if len(user) > 0:
            hashed = User.objects.get(username = postData['username']).password.encode('utf-8')
            password = postData['password'].encode('utf-8')
            if bcrypt.hashpw(password,hashed) == hashed:
                sessionData['id'] = User.objects.get(username = postData['username']).id
                return True
            else:
                return False

# Create your models here.
class User(models.Model):
    name = models.CharField(max_length=50)
    username = models.CharField(max_length=50)
    password = models.CharField(max_length=50)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateField(auto_now=True)
    objects = UserManager()

apps/loginapp/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse
# Create your views here.
def index(request):
    return render(request, "loginapp/index.html")
def register(request):
    result = User.objects.register(request.POST)
    if result['status'] == False:
        for error in result['error']:
            messages.error(request,error)
    else:
        messages.success(request,"Success, user has been created")
    return redirect(reverse("loginapp:index"))
def login(request):
    result = User.objects.login(request.POST, request.session)
    if result == True:
        return redirect("eventapp:index")
    else:
        messages.error(request,"Error, login failed, try again")
        return redirect(reverse("loginapp:index"))

apps/loginapp/templates/loginapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <h2>Registration</h2>
    <form action = "{% url 'loginapp:register' %}", method = "POST">
        {% csrf_token %}
    Name: <input type="text" name="name" value=""><br>
    Username: <input type="text" name="username" value=""><br>
    Password: <input type="text" name="password" value=""><br>
    Confirm Password: <input type="text" name="cpassword" value=""><br>
    <input type="submit" name= value="Submit">
    </form>
    <br><br>
    <h2>Login</h2>
    <form action="{% url 'loginapp:login' %}" method="POST">
        {%csrf_token%}
        Username: <input type="text" name="username" value=""><br>
        Password: <input type="password" name="password" value=""><br>
        <input type="submit" name="" value="Submit">
    </form>
    <br><br>
    {%if messages%}
    {%for message in messages%}
    {{message}}
    <br>
    {%endfor%}
    {%endif%}
</body>
</html>