apps/eventapp/urls.py
from django.conf.urls import url
from . import views
app_name = "eventapp"
urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^add$', views.add, name='add'),
    url(r'^addevent$', views.addevent, name='addevent'),
    url(r'^addactivity/(?P<event_id>\d+)$', views.addactivity, name='addactivity'),
    url(r'^addgoal/(?P<event_id>\d+)$', views.addgoal, name='addgoal'),
    url(r'^view/(?P<event_id>\d+)$', views.view, name='view'),
    url(r'^join/(?P<event_id>\d+)$', views.join, name='join'),
]

events/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginapp.urls', namespace = "loginapp")),
    url(r'^main/', include('apps.eventapp.urls', namespace = "eventapp")),
]

trips/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('apps.loginapp.urls', namespace = "loginapp")),
    url(r'^main/', include('apps.tripapp.urls', namespace = "tripapp")),
]

apps/eventapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from ..loginapp .models import User
from django.db import models

# Create your models here.
class EventManager(models.Manager):
    def createEvent(self, postData, user):
        result = {'status':True, 'error':[]}
        if not postData['destination']:
            result['status'] = False
            result['error'].append('Destination is empty')
        if not postData['description'] or postData['description'] < 3:
            result['status'] = False
            result['error'].append('Please enter a description')
        if not postData['travel_from']:
            result['status'] = False
            result['error'].append('Enter event start date')
        if not postData['travel_to']:
            result['status'] = False
            result['error'].append('Enter event end date')
        if postData['travel_to'] < postData['travel_from']:
            result['status'] = False
            result['error'].append('End date is before Start date, please try again')
        if result['status'] == True:
            Event.objects.create(
                destination = postData['destination'],
                description = postData['description'],
                travel_from = postData['travel_from'],
                travel_to = postData['travel_to'],
                created = user
            )
        return result

class Event(models.Model):
    destination = models.CharField(max_length=50)
    description = models.CharField(max_length=50)
    travel_from = models.DateField()
    travel_to = models.DateField()
    created = models.ForeignKey(User)
    user = models.ManyToManyField(User, related_name='events')
    objects = EventManager()    

class ActivityManager(models.Manager):
    def createActivity(self, postData, user, event):
        result = {'status':True, 'error':[]}
        if not postData['note']:
            result['status'] = False
            result['error'].append('Enter note')
        if not postData['distance']:
            result['status'] = False
            result['error'].append('Enter distance')
        if result['status'] == True:
            Activity.objects.create(
                note = postData['note'],
                distance = postData['distance'],
                created = user,
                event = event
            )
        return result

class Activity(models.Model):
    note = models.CharField(max_length=50)
    distance = models.CharField(max_length=50)
    created = models.ForeignKey(User)
    event = models.ForeignKey(Event)
    objects = ActivityManager()    

class GoalManager(models.Manager):
    def createGoal(self, postData, user, event):
        result = {'status':True, 'error':[]}
        if not postData['goal']:
            result['status'] = False
            result['error'].append('Enter goal')
        if result['status'] == True:
            Goal.objects.create(
                goal = postData['goal'],
                created = user,
                event = event
            )
        return result

class Goal(models.Model):
    goal = models.CharField(max_length=50)
    created = models.ForeignKey(User)
    event = models.ForeignKey(Event)
    objects = GoalManager() 

apps/eventapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from .models import User, Event, Activity, Goal
from django.contrib import messages
from django.db.models import Q

# Create your views here.
def index(request):
    if 'id' not in request.session:
        return redirect(reverse('loginapp:index'))
    user = User.objects.get(id = request.session['id'])
    context = {
        "user": user,
        "events": Event.objects.filter(Q(created = user) | Q(user = user)),
        "other": Event.objects.exclude(Q(created = user) | Q(user = user)),
    }
    return render(request, "eventapp/index.html", context)
def add(request):
    if 'id' not in request.session:
        return redirect(reverse('loginapp:index'))
    return render(request, 'eventapp/add.html')
def addevent(request):
    user = User.objects.get(id = request.session['id'])
    result = Event.objects.createEvent(request.POST, user)
    if result['status'] == False:
        for error in result['error']:
            messages.error(request, error)
        return redirect(reverse("eventapp:add"))
    return redirect(reverse("eventapp:index"))
def addactivity(request, event_id):
    user = User.objects.get(id = request.session['id'])
    event = Event.objects.get(id = event_id)
    result = Activity.objects.createActivity(request.POST, user, event)
    if result['status'] == False:
        for error in result['error']:
            messages.error(request, error)
        # return redirect(reverse("eventapp:add"))
    return redirect(reverse("eventapp:index"))
def addgoal(request, event_id):
    user = User.objects.get(id = request.session['id'])
    event = Event.objects.get(id = event_id)
    result = Goal.objects.createGoal(request.POST, user, event)
    if result['status'] == False:
        for error in result['error']:
            messages.error(request, error)
        # return redirect(reverse("eventapp:add"))
    return redirect(reverse("eventapp:index"))
def view(request, event_id):
    if 'id' not in request.session:
        return redirect(reverse('loginapp:index'))
    user = User.objects.get(id = request.session['id'])
    event = Event.objects.get(id = event_id)
    context = { 
        "event" : event,
        "goers" : event.user.all(),
        "activities" : Activity.objects.filter(created = user).filter(event = event),
        "personalgoal" : Goal.objects.filter(created = user).filter(event = event),
    }
    print(Goal.objects.filter(created = user).filter(event = event).count())
    return render(request, 'eventapp/view.html', context)
def join(request, event_id):
    event = Event.objects.get(id = event_id)
    event.user.add(User.objects.get(id = request.session['id']))
    return redirect(reverse('eventapp:index'))
def logout(request):
    request.session.pop('id')
    return redirect(reverse("loginapp:index"))

apps/eventapp/templates/eventapp/add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    <a href="{% url 'eventapp:index' %}">Home</a>
    <a href="{% url 'eventapp:logout' %}">Logout</a><br>
    <h1>Add a event</h1>
    <form action = "{% url 'eventapp:addevent' %}", method = "POST">
        {% csrf_token %}
    Event name: <input type="text" name="destination"><br>
    Description: <input type="text" name="description"><br>
    From: <input type="date" name="travel_from"><br>
    To: <input type="date" name="travel_to"><br>
    <input type="submit" name= value="Submit">
    </form>
    {%for message in messages%}
        <p>{{message}}</p>
    {%endfor%}
</body>
</html>

apps/eventapp/templates/eventapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    Hello, {{user.name}}
    <a href="{% url 'eventapp:logout' %}">Logout</a><br>
    <br>
    <h2>Your Events</h2>
    <table border="1">
        <tr>
            <th>Event</th>
            <th>Event Start Date</th> 
            <th>Event End Date</th>
            <th>Plan</th>
        </tr>
        {%for event in events%}
        <tr>
            <td><a href="{% url 'eventapp:view' event.id%}">{{event.destination}}</a></td>
            <td>{{event.travel_from}}</td> 
            <td>{{event.travel_to}}</td>
            <td>{{event.description}}</td>
        </tr>
        {%endfor%}
    </table>
    <br>
    <h2>Other User's Events</h2>
    <table border="1">
        <tr>
            <th>Name</th>
            <th>Event</th>
            <th>Travel Start Date</th> 
            <th>Travel End Date</th>
            <th>Do You Want To Join?</th>
        </tr>
        {%for event in other%}
        <tr>
            <td>{{event.created.name}}</td>
            <td><a href="{% url 'eventapp:view' event.id%}">{{event.destination}}</a></td>
            <td>{{event.travel_from}}</td> 
            <td>{{event.travel_to}}</td>
            <td><a href="{% url 'eventapp:join' event.id%}">Join</a></td>
        </tr>
        {%endfor%}
    </table>
    <br>
    <a href="{% url 'eventapp:add' %}">Add event</a>
</body>
</html>

apps/eventapp/templates/eventapp/view.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
    <body>
        <a href="{% url 'eventapp:index' %}">Home</a>
        <a href="{% url 'eventapp:logout' %}">Logout</a><br>
        <h1>{{event.destination}}</h1>
        <p>Planned By: {{event.created.name}}</p>
        <p>Description: {{event.description}}</p>
        <p>Travel Date From: {{event.travel_from}}</p>
        <p>Travel Date To: {{event.travel_to}}</p>

        <!-- <h2>Other users joining the event:</h2>
        {%for user in goers%}
            <p>{{user.name}}</p>
        {%endfor%} -->

        {% if personalgoal.count == 0 %}
        <h2>Add a Goal</h2>
        <form action = "{% url 'eventapp:addgoal' event.id%}", method = "POST">
            {% csrf_token %}
        Goal: <input type="text" name="goal"><br>
        <input type="submit" name= value="Submit">
        </form>
        {% else %}
        <h3>Goal: {{personalgoal.first.goal}}</h3>
        {% endif %}

        <h2>Activities</h2>
        <table border="1">
            <tr>
                <th>Note</th>
                <th>Distance</th>
            </tr>
            {%for activity in activities%}
            <tr>
                <td>{{activity.note}}</td>
                <td>{{activity.distance}}</td>
            </tr>
            {%endfor%}
        </table>

        <h2>Add a activity</h2>
        <form action = "{% url 'eventapp:addactivity' event.id%}", method = "POST">
            {% csrf_token %}
        Note: <input type="text" name="note"><br>
        Distance: <input type="text" name="distance"><br>
        <input type="submit" name= value="Submit">
        </form>
        {%for message in messages%}
            <p>{{message}}</p>
        {%endfor%}
    </body>
</html>